steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-devops/handson:$SHORT_SHA",
        ".",
      ]
    dir: "./"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-devops/handson:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/devops-handson-deployment"
      - "myapp=asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-devops/handson:$SHORT_SHA"
      - "-n"
      - "devops-handson-ns"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=k8s-devops-handson"
